questionBank = [
    { "question": "電腦中當數值資料帶有小數時，其資料的表示法為？", "options": ["整數表示法", "浮點表示法", "字元表示法", "科學符號"], "answer": "浮點表示法" },
    { "question": "個人數位助理的英文簡稱為下列何者？", "options": ["PDA", "IC", "PC", "WWW"], "answer": "PDA" },
    { "question": "將電腦關機斷電時，存在於隨機存取記憶體（RAM）中的資料會如何？", "options": ["消失", "永不消失", "自動儲存到磁片內", "自動儲存到硬碟內"], "answer": "消失" },
    { "question": "下列何者是第一部具有內儲程式的電子計算機？", "options": ["EDSAC", "MARK-1", "ENIAC", "ABC"], "answer": "EDSAC" },
    { "question": "下列關於市面上流行的 iPod 的敘述，何者有誤？", "options": ["蘋果電腦公司(Apple)所生產", "可以播放音樂及影片等多媒體", "可拿來當隨身碟使用", "採用 DDR3 為儲存媒體，可讀可寫"], "answer": "採用 DDR3 為儲存媒體，可讀可寫" },
    { "question": "電子計算機依其發展的歷史，下列敘述何者不正確？", "options": ["硬體架構愈來愈精簡", "CPU 執行速度愈來愈快", "可靠度及穩定性愈來愈高", "記憶體容量愈來愈大"], "answer": "硬體架構愈來愈精簡" },
    { "question": "將電路的所有元件，如電晶體、電阻、二極體等濃縮在一個矽晶片上之電腦元件稱為？", "options": ["真空管", "電晶體", "積體電路", "中央處理單元"], "answer": "積體電路" },
    { "question": "積體電路的英文簡稱是？", "options": ["CPU", "IC", "CAI", "MIS"], "answer": "IC" },
    { "question": "計算機的硬體架構，包括了輸入裝置、輸出裝置，以及下列那一單元？", "options": ["作業系統單元", "中央處理單元", "公用程式單元", "輔助儲存記憶體"], "answer": "中央處理單元" },
    { "question": "下列何者不是電腦特性之一？", "options": ["可以處理中文", "快速運算能力", "記憶容量大", "正確性高"], "answer": "可以處理中文" },
    { "question": "具有環保意識能節省能源的電腦稱為？", "options": ["黑色電腦", "白色電腦", "綠色電腦", "藍色電腦"], "answer": "綠色電腦" },
    { "question": "正確的鍵盤操作法，兩手的食指要經常垂直輕放在下列何者按鍵上？", "options": ["F 與 J", "F 與 G", "J 與 D", "D 與 K"], "answer": "F 與 J" },
    { "question": "目前電腦尚無法達成下列功能？", "options": ["輔助教學", "益智遊戲", "辦公室自動化", "生小孩"], "answer": "生小孩" },
    { "question": "一般我們常說的 PC 是指？", "options": ["迷你電腦", "大型電腦", "個人電腦", "超大型電腦"], "answer": "個人電腦" },
    { "question": "世界上第一部電腦，是採用了以下列何種元件製造？", "options": ["真空管", "電晶體", "積體電路", "微處理器"], "answer": "真空管" },
    { "question": "下列何者是由中國人發明最早期的計量工具？", "options": ["電腦", "卡片處理機", "算盤", "數位計算機"], "answer": "算盤" },
    { "question": "依據電子計算機的演進過程，下列順序那一項為正確？", "options": ["d,a,b,c", "d,c,b,a", "d,c,a,b", "a,b,c,d"], "answer": "d,c,b,a" },
    { "question": "依據使用之電子元件我們將電腦分成第一代、第二代、第三代、第四代等，各代使用的元件以下對應何者正確？", "options": ["第一代：電晶體", "第二代：積體電路", "第三代：真空管", "第四代：超大型積體電路"], "answer": "第四代：超大型積體電路" },
    { "question": "下列關於電腦的相關敘述，何者有誤？", "options": ["IBM 深藍超級電腦因為具有 HDTV 的顯像能力，進而擁有高段棋力，足以挑戰當今西洋棋的棋王", "發展中的第 5 代電腦是科學家想將 AI 方面的知識應用於電腦的設計之中", "市面上流行的筆記型電腦一般而言是屬於個人電腦，也是微電腦的一種", "將計算工作分送給網路上 CPU 處於閒置的個人電腦進行協同運算，這是一種分散處理的形式"], "answer": "IBM 深藍超級電腦因為具有 HDTV 的顯像能力，進而擁有高段棋力，足以挑戰當今西洋棋的棋王" },
    { "question": "下列敘述何者正確？", "options": ["PDA 是屬於超級電腦", "iPod 是屬於嵌入式電腦", "MP4 播放器是屬於大型電腦", "Blog 是屬於第4代電腦"], "answer": "iPod 是屬於嵌入式電腦" },
    { "question": "台灣高鐵網路購票系統的資料處理特性，最不可能包含以下何種？", "options": ["離線處理", "集中處理", "分散處理", "連線處理"], "answer": "離線處理" },
    { "question": "RGB 模式所使用的是哪幾種顏色？", "options": ["紅、綠、黃", "紅、綠、藍", "青、粉紅、白", "藍、黃、黑"], "answer": "紅、綠、藍" },
    { "question": "下列哪一種自動化在產品設計、建築設計、電路板設計等領域均適用？", "options": ["CAI", "CAD", "CAE", "CAM"], "answer": "CAD" },
    { "question": "哪種類型的圖檔常用於不同軟體與平台間的轉換，適合印刷輸出？", "options": ["TIFF", "JPEG", "BMP", "GIF"], "answer": "TIFF" },
    { "question": "在電腦演進中，哪一代電腦使用人工智慧（AI）的觀念，讓電腦具有自我學習與思考判斷的能力？", "options": ["第一代", "第三代", "第四代", "第五代"], "answer": "第五代" },
    { "question": "若想要用數位相機拍照，再由相片印表機輸出而且不失真，相片印表機的解析度為 300dpi，輸出相片尺寸為 4 吋 × 6 吋，則數位相機的解析度至少需要多少畫素？", "options": ["200 萬", "100 萬", "600 萬", "300 萬"], "answer": "300 萬" },
    { "question": "下列哪一項不是全球定位系統（GPS）技術主要的應用？", "options": ["汽車失竊查找", "手機無線上網", "飛機導航", "汽車路線追蹤"], "answer": "手機無線上網" },
    { "question": "下列有關語音檔案的副檔名何者不正確？", "options": [".MDB", ".AU", ".MIDI", ".MP3"], "answer": ".MDB" },
    { "question": "下列何者屬於辦公室自動化的範疇？", "options": ["電腦輔助製造", "資訊家電", "試算表軟體", "SOHO"], "answer": "試算表軟體" },
    { "question": "有關臺灣學術網路的敘述，何者有誤？", "options": ["英文名稱為 TANet", "由資策會所負責", "支援教學、研究為目的", "供學術及研究單位免費使用"], "answer": "由資策會所負責" },
    { "question": "小明靠著車上的衛星導航系統玩遍全台灣，主要是藉由哪一種技術？", "options": ["GPS", "CAI", "WWW", "Skype"], "answer": "GPS" },
    { "question": "下列哪一個不是電子商務的範圍？", "options": ["商業交易", "硬體設計", "金融匯兌", "市場情報"], "answer": "硬體設計" },
    { "question": "為了節省及考慮飛行員安全所設計的模擬飛行器，主要是哪一方面的應用？", "options": ["CAI", "SOHO", "VR", "WWW"], "answer": "VR" },
    { "question": "觀賞網路線上影片，會先行下載影片的前一部分，在播放前段影片的同時也持續下載剩餘部份，此種方法稱為？", "options": ["串流技術", "交錯顯示", "燒不死技術", "推播技術"], "answer": "串流技術" },
    { "question": "近來流行於 Internet 上的 DivX 串流檔其視訊壓縮是採用？", "options": ["MPEG-4", "MP3", "AAC", "JPEG"], "answer": "MPEG-4" },
    { "question": "音樂 CD 使用的數位量化頻率約？", "options": ["1.1KHz", "11.1KHz", "22.1KHz", "44.1KHz"], "answer": "44.1KHz" },
    { "question": "下列何者不是影音播放程式？", "options": ["Windows Media Player", "RealPlayer", "QuickTime", "CorelDRAW"], "answer": "CorelDRAW" },
    { "question": "下列電腦相關英文簡稱，何者有誤？", "options": ["地理資訊系統：MIS", "電腦輔助設計：CAD", "虛擬實境：VR", "人工智慧：AI"], "answer": "地理資訊系統：MIS" },
    { "question": "醫院的醫護人員使用稱為「個人數位助理」的掌上型電腦來記錄病患資訊，所謂的「個人數位助理」簡稱為？", "options": ["CAD", "GPS", "PDA", "IA"], "answer": "PDA" },
    { "question": "MP4 格式的檔案屬於一種？", "options": ["只針對聲音進行壓縮的 DVD 影像檔", "無失真的影音壓縮檔", "有失真的文字壓縮檔", "包含聲音和影像"], "answer": "包含聲音和影像" },
    { "question": "在計算機硬體結構的五大單元中，那一單元負責協調及指揮各單元間的運作？", "options": ["記憶單元", "輸入/輸出單元", "算術邏輯單元", "控制單元"], "answer": "控制單元" },
    { "question": "電腦的基本架構中，記憶單元(主記憶體)、算術及邏輯單元、以及控制單元三者合稱為？", "options": ["ALU", "CPU", "OS", "RAM"], "answer": "CPU" },
    { "question": "由輸入單元所輸入的程式或資料存於電腦的那一部份？", "options": ["中央處理器", "記憶體", "控制器", "以上皆非"], "answer": "記憶體" },
    { "question": "通常把電腦的硬體分成幾大部門？", "options": ["四", "五", "六", "七"], "answer": "五" },
    { "question": "主記憶體的 RAM 為？", "options": ["只能讀出資料，不能寫入資料", "可隨意讀出或寫入資料", "不能讀出資料，只能寫入資料", "都不能讀寫資料"], "answer": "可隨意讀出或寫入資料" },
    { "question": "下列何者不是硬體的五大部門？", "options": ["算術邏輯單元", "控制單元", "磁碟作業系統", "記憶體單元"], "answer": "磁碟作業系統" },
    { "question": "電腦內部所能表示的最基本單位，稱為？", "options": ["位元組", "位元", "百位元組", "千位元組"], "answer": "位元" },
    { "question": "下列那一項為「並列式插座」的簡稱？", "options": ["PS/2", "LPT", "COM", "USB"], "answer": "LPT" },
    { "question": "下列那一個為液晶顯示器的簡稱？", "options": ["LPT", "PDA", "CRT", "LCD"], "answer": "LCD" },
    { "question": "所謂 20 吋螢幕是指？", "options": ["螢幕的對角線長度", "螢幕的寬度", "螢幕的高度", "螢幕的解析度"], "answer": "螢幕的對角線長度" },
    { "question": "下列何者不是電腦的周邊設備？", "options": ["喇叭", "CPU", "顯示器", "滑鼠"], "answer": "CPU" },
    { "question": "下列關於 USB 2.0 的敘述，何者有誤？", "options": ["具熱插拔功能", "採用並列傳輸方式，速度較快", "最高連接 127 個周邊設備", "只要具備 USB 接頭的周邊設備皆可使用"], "answer": "採用並列傳輸方式，速度較快" },
    { "question": "下列何種裝置常使用 PS/2 埠連接至主機？", "options": ["鍵盤", "喇叭", "雷射印表機", "耳機"], "answer": "鍵盤" },
    { "question": "下列何種設備同時具有列印、影印、掃瞄與傳真等多項功能？", "options": ["影印機", "掃描器", "印表機", "多功能事務機"], "answer": "多功能事務機" },
    { "question": "下列何者屬於輸出設備？", "options": ["掃描器", "麥克風", "條碼閱讀機", "繪圖機"], "answer": "繪圖機" },
    { "question": "下列何者屬於輸入設備？", "options": ["繪圖機", "滑鼠", "印表機", "喇叭"], "answer": "滑鼠" },
    { "question": "所有儲存在輔助記憶體的程式均需載至何處方可執行？", "options": ["硬碟", "主記憶體", "螢幕", "鍵盤"], "answer": "主記憶體" },
    { "question": "有關套裝軟體，下列何者錯誤？", "options": ["Microsoft Access 為資料庫系統軟體", "Microsoft PowerPoint 為試算表軟體", "Microsoft Word 為文書排版軟體", "Adobe Photoshop 為影像處理軟體"], "answer": "Microsoft PowerPoint 為試算表軟體" },
    { "question": "下列何者為電腦硬體中，負責處理「算術和邏輯運算」的單元為何？", "options": ["算術邏輯單元", "輸出單元", "記憶單元", "控制單元"], "answer": "算術邏輯單元" },
    { "question": "「控制單元」的英文簡稱為下列何者？", "options": ["PC", "CU", "ALU", "CPU"], "answer": "CU" },
    { "question": "「算術邏輯單元」的英文簡稱為下列何者？", "options": ["PC", "CU", "ALU", "CPU"], "answer": "ALU" },
    { "question": "「中央處理機」的英文簡稱為下列何者？", "options": ["PC", "CU", "ALU", "CPU"], "answer": "CPU" },
    { "question": "一般稱主記憶體時，大多是指？", "options": ["RMA", "MAR", "MRA", "RAM"], "answer": "RAM" },
    { "question": "一般用來儲存製造廠商所提供的系統操作程式是下列何種記憶體？", "options": ["RAM", "ROM", "FLOPPY DISK", "HD"], "answer": "ROM" },
    { "question": "可執行資料的加、減、乘、除等計算，是屬於什麼功能？", "options": ["計算判斷", "記憶", "控制", "輸入"], "answer": "計算判斷" },
    { "question": "可以控制電腦主機與週邊設備的舉止活動，是屬於電腦的何種功能？", "options": ["計算判斷", "記憶", "控制", "輸入"], "answer": "控制" },
    { "question": "下列何種記憶體，可隨意讀出或寫入程式與資料？", "options": ["RAM", "ROM", "PROM", "EPROM"], "answer": "RAM" },
    { "question": "下列何種記憶體，電源消失後，資料也會消失？", "options": ["RAM", "ROM", "PROM", "EPROM"], "answer": "RAM" },
    { "question": "只能讀出已儲存的資料，而不能被寫入任何程式或資料的記憶體是哪種？", "options": ["RAM", "ROM", "SRAM", "DRAM"], "answer": "ROM" },
    { "question": "下列何者不屬於輔助記憶體的種類？", "options": ["磁碟", "磁帶", "光碟", "螢幕"], "answer": "螢幕" },
    { "question": "下列儲存媒體之資料存取時間，以何種為最短？", "options": ["硬碟", "光碟", "軟碟", "隨機存取記憶體(RAM)"], "answer": "隨機存取記憶體(RAM)" },
    { "question": "就 CPU 存取資料而言，下列那種儲存的速度最快？", "options": ["硬式磁碟", "主記憶體", "快取記憶體", "暫存器"], "answer": "暫存器" },
    { "question": "下列那一個裝備不是電腦的輸出裝備？", "options": ["磁碟機", "繪圖機", "數位相機", "螢光幕"], "answer": "數位相機" },
    { "question": "下列何種設備兼具輸入及輸出功能？", "options": ["滑鼠", "鍵盤", "磁碟機", "光學閱讀機"], "answer": "磁碟機" },
    { "question": "輸入與輸出單元合併稱之為：", "options": ["中央處理單元", "週邊設備", "輔助記憶體", "控制部門"], "answer": "週邊設備" },
    { "question": "硬碟結構中的系統區，檔案的真實位置被完整記錄在那一區中？", "options": ["硬碟分割區", "檔案配置區", "根目錄區", "啟動區"], "answer": "檔案配置區" },
    { "question": "電腦記憶體容量大小的單位通常用 KB、TB、GB 或 MB 表示，這四種單位，由大到小的排列為？", "options": ["KB > TB > GB > MB", "GB > TB > MB > KB", "TB > GB > MB > KB", "MB > KB > TB > GB"], "answer": "TB > GB > MB > KB" },
    { "question": "下列關於暫存器的敘述何者有誤？", "options": ["屬於記憶體的一種", "位於 CPU 的外部", "暫存正在執行的指令位址或資料", "執行速度快，但價格高"], "answer": "位於 CPU 的外部" },
    { "question": "磁碟製造出來時，只是一片塗有磁性物質的裝置，並不能馬上用來存放資料；一片新的磁碟必須在完成？工作之後才能存放資料", "options": ["格式化", "磁碟清理", "磁碟重組", "檔案管理"], "answer": "格式化" },
    { "question": "商品包裝上的條碼(barcode)，係作為客戶結帳或庫存盤點之用，則此「條碼」在資料處理作業上是屬於下列何者？", "options": ["輸入設備", "輸出設備", "輸入媒體", "輸出媒體"], "answer": "輸入媒體" },
    { "question": "金融機構的提款卡，可提供使用者進行提款作業，則該「提款卡」在資料處理作業上是屬於下列何者？", "options": ["輸入設備", "輸出設備", "輸入媒體", "輸出媒體"], "answer": "輸入媒體" },
    { "question": "下列何者為電腦硬體中，負責儲存輸入的資料、程式和處理結果的單元？", "options": ["輸入單元", "輸出單元", "記憶單元", "控制單元"], "answer": "記憶單元" },
    { "question": "下列何者為電腦硬體中，負責控制各單元的執行？", "options": ["輸入單元", "輸出單元", "記憶單元", "控制單元"], "answer": "控制單元" },
    { "question": "下列何種輔助記憶體，會依照順序讀取資料？", "options": ["軟式磁碟", "硬式磁碟", "磁帶", "光碟"], "answer": "磁帶" },
    { "question": "下列何者只能做為輸出裝置？", "options": ["印表機", "鍵盤", "滑鼠", "光筆"], "answer": "印表機" },
    { "question": "下列何者只能做為輸出裝置？", "options": ["繪圖機", "鍵盤", "滑鼠", "光筆"], "answer": "繪圖機" },
    { "question": "下列何者只能當做輸入裝置？", "options": ["繪圖機", "列表機", "螢幕", "滑鼠"], "answer": "滑鼠" },
    { "question": "下列何者只能當做輸入裝置？", "options": ["繪圖機", "列表機", "螢幕", "掃描器"], "answer": "掃描器" },
    { "question": "下列何者只能當做輸入裝置？", "options": ["繪圖機", "列表機", "螢幕", "鍵盤"], "answer": "鍵盤" },
    { "question": "下列何者只能當做輸入裝置？", "options": ["繪圖機", "列表機", "螢幕", "光筆"], "answer": "光筆" },
    { "question": "下列何者只能當做輸入裝置？", "options": ["繪圖機", "列表機", "螢幕", "讀卡機"], "answer": "讀卡機" },
    { "question": "下列何者同時具有輸入功能和輸出功能的裝置？", "options": ["滑鼠", "列表機", "硬式磁碟機", "掃描器"], "answer": "硬式磁碟機" },
    { "question": "下列何者同時具有輸入功能和輸出功能的裝置？", "options": ["滑鼠", "列表機", "軟式磁碟機", "掃描器"], "answer": "軟式磁碟機" },
    { "question": "能顯示使用者輸入的命令和資料，並顯示電腦經過處理結果的週邊設備是？", "options": ["鍵盤", "螢幕", "滑鼠", "印表機"], "answer": "螢幕" },
    { "question": "能列印電腦經過處理後之結果的週邊設備是下列何者？", "options": ["鍵盤", "螢幕", "滑鼠", "印表機"], "answer": "印表機" },
    { "question": "能輸入文字及圖表至電腦的週邊設備是下列何者？", "options": ["繪圖機", "螢幕", "掃描器", "印表機"], "answer": "掃描器" },
    { "question": "通常運用在電腦繪圖上，它透過一條電線與電腦連接，在桌面上移動時，螢幕上的游標也跟著移動的週邊設備是？", "options": ["鍵盤", "掃描器", "讀卡機", "滑鼠"], "answer": "滑鼠" },
    { "question": "用來輸入命令和打入資料的週邊設備為？", "options": ["滑鼠", "印表機", "鍵盤", "掃描器"], "answer": "鍵盤" },
    { "question": "電腦可儲存大量的資料就像人的？", "options": ["心臟", "腦", "手", "神經系統"], "answer": "腦" },
    { "question": "在電腦系統中，記憶單元負責下列何者工作？", "options": ["資料輸入", "資料輸出", "資料指令的執行", "儲存輸入的資料，程式和處理結果"], "answer": "儲存輸入的資料，程式和處理結果" },
    { "question": "個人電腦中鍵盤的大寫鎖定鍵為下列何者？", "options": ["Caps Lock", "Scroll Lock", "BackSpace", "Num Lock"], "answer": "Caps Lock" },
    { "question": "個人電腦中鍵盤的數字鎖定鍵為下列何者？", "options": ["Caps Lock", "Scroll Lock", "BackSpace", "Num Lock"], "answer": "Num Lock" },
    { "question": "電腦軟碟與硬碟的比較，下列何者錯誤？", "options": ["軟碟片容量較小", "硬碟速度較慢", "軟碟片較易發霉", "有 120MB 容量的軟碟片"], "answer": "硬碟速度較慢" },
    { "question": "儲存在電腦裡的資料，通常稱它為下列何者？", "options": ["光碟", "軟碟", "硬碟", "檔案"], "answer": "檔案" },
    { "question": "桌上型個人電腦的鍵盤依其功能的不同，主要可區分為幾部分？", "options": ["三", "四", "五", "六"], "answer": "四" },
    { "question": "電腦硬體五大單元中，哪個單元負責讀取並轉換媒體內的資料？", "options": ["輸入單元", "輸出單元", "記憶單元", "算術邏輯單元"], "answer": "輸入單元" },
    { "question": "下列有關 RAM（Random Access Memory）的敘述，何者有誤？", "options": ["用來暫存執行中的程式及資料", "屬於不揮發性記憶體", "屬於主記憶體", "平常所稱某部電腦有多少主記憶體（如 1GB），指的是 DRAM"], "answer": "屬於不揮發性記憶體" },
    { "question": "下列何者為輸出設備？", "options": ["印表機", "滑鼠", "鍵盤", "搖桿"], "answer": "印表機" },
    { "question": "電腦的螢幕是屬於？", "options": ["輸入設備", "文字設備", "輸出設備", "機械設備"], "answer": "輸出設備" },
    { "question": "電腦的滑鼠是屬於？", "options": ["文字設備", "輸入設備", "輸出設備", "機械設備"], "answer": "輸入設備" },
    { "question": "下列何者是控制鍵？", "options": ["Ctrl", "Esc", "Shift", "Alt"], "answer": "Ctrl" },
    { "question": "下列何者是轉換鍵？", "options": ["Esc", "Alt", "Caps Lock", "Shift"], "answer": "Alt" },
    { "question": "下列何者是跳離鍵？", "options": ["Alt", "Shift", "Esc", "Control"], "answer": "Esc" },
    { "question": "位於鍵盤最上方，通常被用來做特殊用途之按鍵為？", "options": ["打字鍵", "編輯鍵", "數字編輯鍵", "功能鍵"], "answer": "功能鍵" },
    { "question": "可將游標向上、下、左、右移動，每按一次就移動一格的按鍵為？", "options": ["方向鍵", "插入鍵", "退位鍵", "轉換鍵"], "answer": "方向鍵" },
    { "question": "下列何者是插入鍵？", "options": ["Del", "Insert", "Alt", "Esc"], "answer": "Insert" },
    { "question": "下列何者是刪除鍵？", "options": ["Alt", "Esc", "Del", "Insert"], "answer": "Del" },
    { "question": "下列何者是定位鍵？", "options": ["Tab", "Shift", "Esc", "Alt"], "answer": "Tab" },
    { "question": "鍵盤中與其他鍵配合，可產生控制功能的是？", "options": ["轉換鍵", "跳離鍵", "退位鍵", "控制鍵"], "answer": "控制鍵" },
    { "question": "一個硬碟通常由數片碟片相疊而成，每張碟片上編號相同的磁軌所形成的空心圓柱稱之為？", "options": ["磁柱", "磁區", "磁碟", "磁叢"], "answer": "磁柱" },
    { "question": "新一代的藍光 DVD（BD，Blu-ray Disc），單面單層的光碟片容量約為？", "options": ["8.5GB", "17GB", "25GB", "50GB"], "answer": "25GB" },
    { "question": "固態硬碟 SSD 讀取速度比傳統硬碟快，也較省電，採用的材質是下列哪一種？", "options": ["硬式碟片", "快閃記憶體", "藍光光碟片", "快取記憶體"], "answer": "快閃記憶體" },
    { "question": "下列何者為唯讀記憶體的英文名稱？", "options": ["RAM", "CPU", "ROM", "HD"], "answer": "ROM" },
    { "question": "下列何者為隨機存取記憶體的英文名稱？", "options": ["ROM", "CPU", "HD", "RAM"], "answer": "RAM" },
    { "question": "下列何種屬於輔助記憶體？", "options": ["印表機", "繪圖機", "磁碟機", "打字機"], "answer": "磁碟機" },
    { "question": "下列何者是利用雷射光束反射回來的信號讀取資料？", "options": ["磁碟片", "硬碟", "光碟片", "卡片"], "answer": "光碟片" },
    { "question": "光筆是何種週邊設備？", "options": ["輸出", "輸入", "輸入輸出皆可", "與輸入輸出無關"], "answer": "輸入" },
    { "question": "掃描器是何種週邊設備？", "options": ["輸入", "輸出", "輸入輸出皆可", "與輸入輸出無關"], "answer": "輸入" },
    { "question": "電腦鍵盤上共有幾個英文字母鍵？", "options": ["25", "26", "27", "28"], "answer": "26" },
    { "question": "多媒體市場儲存媒體的主流是？", "options": ["磁片", "錄音帶", "卡片", "光碟片"], "answer": "光碟片" },
    { "question": "下列敘述何者有錯誤？", "options": ["使用電腦時應遠離電器避免磁場干擾", "隨時保持電腦鍵盤、螢幕、主機清潔", "電腦可經常移動不怕碰撞", "避免日照、高溫、油污"], "answer": "電腦可經常移動不怕碰撞" },
    { "question": "電腦最好遠離電器，其主要原因，是避免何種干擾？", "options": ["磁場", "濕氣", "溫度", "美觀"], "answer": "磁場" },
    { "question": "小熊想要為家中的電腦加裝一顆硬碟，如果他希望購買傳輸速度較快的硬碟，他應考慮選購下列哪一種介面的硬碟？", "options": ["AGP", "S-ATA", "IDE", "PCI"], "answer": "S-ATA" },
    { "question": "用來監督管理電腦所有資源的軟體為？", "options": ["管理資訊系統", "作業系統", "檔案系統", "I/O 系統"], "answer": "作業系統" },
    { "question": "電腦系統中，負責資源調派與作業管理的軟體是？", "options": ["系統程式", "公用程式", "應用程式", "資料庫管理程式"], "answer": "系統程式" },
    { "question": "將類似資料收集起來於固定時間一起處理的作業方式稱為？", "options": ["連線處理", "批次處理", "即時處理", "分時處理"], "answer": "批次處理" },
    { "question": "下列那一項不是作業系統的功能？", "options": ["檔案管理", "磁碟管理", "記憶體管理", "個人財務管理"], "answer": "個人財務管理" },
    { "question": "在作業系統中負責管理行程的啟動與結束，並在行程的執行過程中，協調電腦資源配置的是作業系統中的那一項功能？", "options": ["檔案管理", "行程管理", "保護系統", "控制台"], "answer": "行程管理" },
    { "question": "每月列印員工薪資明細表的作業，適合使用下列那一種作業系統？", "options": ["批次處理作業系統", "即時處理作業系統", "分時處理作業系統", "多工處理作業系統"], "answer": "批次處理作業系統" },
    { "question": "銀行的每半年一次的計息工作，適合使用下列那一種作業方式？", "options": ["即時處理作業", "交談式處理作業", "批次處理作業", "平行式處理作業"], "answer": "批次處理作業" },
    { "question": "郵局自動提款機的資料處理不屬於下列那一種處理方式？", "options": ["整批處理", "即時處理", "連線處理", "分散處理"], "answer": "整批處理" },
    { "question": "下列哪一種方式適合大量且較不需立即處理的資料？", "options": ["批次處理", "線上處理", "即時處理", "分時處理"], "answer": "批次處理" },
    { "question": "到 ATM 去轉帳繳納網購的費用，整個進行的過程是使用下列哪一種資料處理的方式？", "options": ["交談式處理", "批次處理", "分時處理", "離線處理"], "answer": "交談式處理" },
    { "question": "未經整理過或不具意義的文數字符號，稱之為？", "options": ["資訊（Information）", "資料（Data）", "資料處理（DP）", "電子資料處理（EDP）"], "answer": "資料（Data）" },
    { "question": "離線（Offline）處理通常是指？", "options": ["處理過程中，CPU 和輸出入設備未保持連結狀態", "各個工作輪流使用 CPU", "集中於某一部電腦處理資料", "接收資料後立即處理及回應"], "answer": "處理過程中，CPU 和輸出入設備未保持連結狀態" },
    { "question": "下列關於電腦演進歷史的相關敘述，何者有誤？", "options": ["何樂禮發明了打孔卡片用以紀錄資料，被尊敬為電腦之父", "巴貝奇發明了差分機，可處理簡單的四則運算", "范紐曼提出「內儲程式」的觀念", "真空管是第一代電腦的主要元件，其中代表性的電腦為 ENIAC"], "answer": "何樂禮發明了打孔卡片用以紀錄資料，被尊敬為電腦之父" },
    { "question": "作業系統提供了一個介於電腦與使用者之間的一個界面，其中該作業系統包含了下列何種功能，使得使用者不需關心檔案之儲存方式與位置？", "options": ["保護系統", "輸出入系統", "記憶體管理系統", "檔案管理系統"], "answer": "檔案管理系統" },
    { "question": "下列作業中，那一項並非作業系統所提供之功能？", "options": ["分時作業 (Time-sharing)", "多工作業 (Multitasking)", "程式翻譯作業 (Language Translation)", "多元程式作業 (Multi-programming)"], "answer": "程式翻譯作業 (Language Translation)" },
    { "question": "下列何者的主要功能是管理與協調電腦的硬體設備，使其能迅速有效地正常運作？", "options": ["應用軟體", "系統軟體", "自製軟體", "套裝軟體"], "answer": "系統軟體" },
    { "question": "協助使用者與應用軟體能方便地使用電腦的是？", "options": ["系統軟體", "套裝軟體", "自製軟體", "工具軟體"], "answer": "系統軟體" },
    { "question": "像一座橋樑，為硬體、使用者和應用軟體之間搭起一座友誼的橋樑是？", "options": ["工具軟體", "自製軟體", "套裝軟體", "系統軟體"], "answer": "系統軟體" },
    { "question": "系統軟體包括？", "options": ["作業系統", "會計系統", "文書處理", "程式語言"], "answer": "作業系統" },
    { "question": "以下那項不是 Windows 作業系統之功能？", "options": ["提供 C 語言的程式", "支援多工環境", "支援長檔名", "網路功能"], "answer": "提供 C 語言的程式" },
    { "question": "在 Windows98/2000/XP 中，使用者可以利用下列何種方法調整鍵盤的反應速度？", "options": ["按住 Ctrl+Alt 鍵的同時，按 + 鍵，加快鍵盤的反應速度", "縮短鍵盤與主機之間的連接線，可加快鍵盤的反應速度", "利用控制台中的鍵盤圖示，可開啟鍵盤內容交談窗，調整鍵盤的反應速度", "在主機鍵盤插孔的右側有一旋鈕，將該旋鈕往逆時針方向旋轉，可加快鍵盤的反應速度"], "answer": "利用控制台中的鍵盤圖示，可開啟鍵盤內容交談窗，調整鍵盤的反應速度" },
    { "question": "下列何者不是視窗導向之操作系統？", "options": ["MS-DOS", "WindowsNT", "Windows2000", "Windows98"], "answer": "MS-DOS" },
    { "question": "當要離開 Windows98/2000/XP 並關閉電腦，以下何種方式為正確的方式？", "options": ["按 PC 上的 Reset 鍵", "關閉 PC 上的電源", "使用開始功能表的關機指令", "按 Ctrl+Alt+Delete 鍵"], "answer": "使用開始功能表的關機指令" },
    { "question": "Linux 作業系統是屬於？", "options": ["系統軟體", "應用軟體", "文書處理軟體", "資料庫管理軟體"], "answer": "系統軟體" },
    { "question": "下列那一項作業系統是屬於多人多工的作業系統？", "options": ["MS-DOS", "OS/2", "Unix", "Windows98"], "answer": "Unix" },
    { "question": "下列哪一種軟體不是作業系統軟體？", "options": ["鐵路訂票系統", "Linux 系統", "UNIX 系統", "微軟視窗作業系統"], "answer": "鐵路訂票系統" },
    { "question": "下列系統何者可幫助使用者管理硬體資源，使電腦發揮最大的效能？", "options": ["作業系統", "媒體", "資料系統", "編修系統"], "answer": "作業系統" },
    { "question": "屬於文字介面的作業系統是以下那一種？", "options": ["DOS", "Windows 98", "Windows 2000", "Windows XP"], "answer": "DOS" },
    { "question": "在 Windows 98/2000/XP 中，可以同時上網又能處理文書資料，同時打電動遊戲又可以聽音樂 CD，這是因為使用以下何種作業方式？", "options": ["分散作業", "多工作業", "網路作業", "批次作業"], "answer": "多工作業" },
    { "question": "下列關於作業系統（OS）的敘述，何者正確？", "options": ["具備圖形介面：Linux、MS-DOS", "開放原始碼：Windows Vista、Linux", "網路作業系統：Windows XP、UNIX", "單人多工：Windows Vista、Mac OS"], "answer": "網路作業系統：Windows XP、UNIX" },
    { "question": "Linux 是哪一種軟體類別？", "options": ["系統軟體", "影音播放軟體", "語言處理軟體", "套裝軟體"], "answer": "系統軟體" },
    { "question": "下列何者不屬於電腦的作業系統（OS）？", "options": ["Window 7", "Palm OS", "UNIX", "CMOS"], "answer": "CMOS" },
    { "question": "作業系統為資源管理者，Windows 所管理之資源範圍不包含下列那一項？", "options": ["檔案管理", "資料庫管理", "記憶體管理", "週邊設備管理"], "answer": "資料庫管理" },
    { "question": "在 Windows 系統中，慣用左手者若欲改變滑鼠之左右鍵功能，應至下列何者更改設定？", "options": ["程式集", "執行", "控制台", "尋找"], "answer": "控制台" },
    { "question": "Windows 中，如果想要選取全部檔案，應配合按住那一個按鍵再選取檔案？", "options": ["Shift 鍵", "Ctrl 鍵", "Ctrl+A", "Shift+A"], "answer": "Ctrl+A" },
    { "question": "在 Windows98/2000/XP 中刪除檔案後，被刪除的檔案將被放置在下列那一項中？", "options": ["資料夾", "剪貼簿", "檔案總管", "資源回收筒"], "answer": "資源回收筒" },
    { "question": "Windows 的檔案目錄是採用下列何種結構？", "options": ["直線圖", "環狀", "樹狀", "星狀"], "answer": "樹狀" },
    { "question": "在 Windows XP 中，關於螢幕畫面解析度的敘述，下列何者錯誤？", "options": ["解析度的設定值和電腦的顯示卡有關", "設定解析度愈高，則螢幕上的物件愈小", "解析度 640X480 的後一個數值是指水平方向的像素個數", "設定解析度愈小，則螢幕上的物件愈少"], "answer": "解析度 640X480 的後一個數值是指水平方向的像素個數" },
    { "question": "當 Windows XP 不正常關機後，再重新開機會自動執行？", "options": ["磁碟清理", "磁碟掃描", "磁碟重組", "磁碟壓縮"], "answer": "磁碟掃描" },
    { "question": "作業系統為資源管理者，MS-Windows 所管理之資源範圍不包含下列那一項？", "options": ["檔案管理", "資料庫管理", "記憶體管理", "週邊設備管理"], "answer": "資料庫管理" },
    { "question": "在 MS-Windows 系統中，慣用左手者若欲改變滑鼠之左右鍵功能，應至下列何者更改設定？", "options": ["程式集", "執行", "控制台", "尋找"], "answer": "控制台" },
    { "question": "在 Windows 2000/XP 中如果要檢視記憶體的使用狀況要使用？", "options": ["系統監視程式", "磁碟清理工具", "磁碟掃瞄工具", "工作管理員"], "answer": "工作管理員" },
    { "question": "哪一種電腦作業系統可為單人多工及多人多工的作業系統？", "options": ["MS-DOS", "Linux", "Windows XP", "Windows Mobile"], "answer": "Linux" },
    { "question": "在作業系統的功能中有一個類別是管理磁碟的檔案，這是屬於下列哪一項功能？", "options": ["圖形化使用者介面", "I/O 設備管理", "通訊網路管理", "檔案系統管理"], "answer": "檔案系統管理" },
    { "question": "磁碟重組的主要功能為？", "options": ["將同一檔案分散各處的資料集合在一起", "可以減少磁頭移動的次數", "可以加速資料存取時間", "以上皆是"], "answer": "以上皆是" },
    { "question": "在 Windows 98/2000/XP 的桌面控制中心，「開始」功能表位於下列何處？", "options": ["工作列上", "控制台", "程式集", "工具列中"], "answer": "工作列上" },
    { "question": "在 Windows XP 的作業環境下，正確的關機方法為何？", "options": ["直接關閉電源", "關閉螢幕電源", "直接拔掉電腦的電源插頭", "在「開始」功能表中選取「關機」項目來關機"], "answer": "在「開始」功能表中選取「關機」項目來關機" },
    { "question": "在 Windows XP 的作業環境下，開機後如果出現登入 Windows 的對話方塊時，需鍵入的資料為何？", "options": ["學號、密碼", "使用者名稱、密碼", "電子郵件信箱、密碼", "班級、密碼"], "answer": "使用者名稱、密碼" },
    { "question": "在 Windows 98/2000/XP 的作業環境下，若要開啟「資料夾」圖示的「快顯功能表」時，先將滑鼠指標移至該「資料夾」圖示上，再操作下列何種動作？", "options": ["按一下滑鼠左鍵", "連按二次滑鼠左鍵", "按一下滑鼠右鍵", "連按二次滑鼠右鍵"], "answer": "按一下滑鼠右鍵" },
    { "question": "在 Windows 98/2000/XP 的作業環境下，若要建立新的資料夾時，預設的名稱為下列何者？", "options": ["未命名", "新檔案", "捷徑", "新資料夾"], "answer": "新資料夾" },
    { "question": "在 Windows98/2000/XP 的作業環境下，若「檔案總管」視窗中的資料夾，前面的符號為「+」時，表示下列何種意義？", "options": ["下層已無資料夾或檔案", "下層只有檔案", "下層只有資料夾", "下層還有資料夾或檔案"], "answer": "下層還有資料夾或檔案" },
    { "question": "在 Windows98/2000/XP 的作業環境下，管理電腦資料夾檔案的應用程式為下列何者？", "options": ["小算盤", "我的最愛", "檔案總管", "程式集"], "answer": "檔案總管" },
    { "question": "在 Windows98/2000/XP 的作業環境下，硬碟中的資料夾或檔案刪除後，還可以從下列那個應用程式救回來？", "options": ["記事本", "剪貼簿", "資源回收筒", "試算表"], "answer": "資源回收筒" },
    { "question": "在視窗作業環境中，於圖示上按滑鼠右鍵產生的快顯功能表不提供下列何種功能？", "options": ["排列圖示", "刪除", "複製", "建立捷徑"], "answer": "排列圖示" },
    { "question": "下列何者是視窗作業系統？", "options": ["DOS", "Windows", "PC-DOS", "BASIC"], "answer": "Windows" },
    { "question": "將滑鼠移到指定位置，按住滑鼠左鍵然後移動滑鼠到新的位置，再放開滑鼠左鍵，稱為？", "options": ["按一下", "按二下", "拖引(曳)", "按三下"], "answer": "拖引(曳)" },
    { "question": "下列何者不是電腦繪圖的優點？", "options": ["節省成本", "存取方便", "整合性佳", "可快速進行文書處理"], "answer": "可快速進行文書處理" },
    { "question": "操作 Windows 的「小畫家」繪圖軟體時，當著色範圍錯誤時，可使用下列那項功能回復到填色前的狀態？", "options": ["編輯／清除", "檔案／清除", "編輯／復原", "編輯／重複"], "answer": "編輯／復原" },
    { "question": "操作 Windows 的「小畫家」繪圖軟體時，想利用滑鼠點選「前景顏色」時，應按滑鼠的何鍵？", "options": ["左鍵", "右鍵", "中間鍵", "不用按任何鍵"], "answer": "左鍵" },
    { "question": "在 Windows 的「小畫家」繪圖軟體中，可將圖案放大便於處理微小圖案的工具是下列何者？", "options": ["放大鏡", "噴槍", "粉刷", "鉛筆"], "answer": "放大鏡" },
    { "question": "在 Windows 的「小畫家」繪圖軟體中，想利用滑鼠選擇「背景色彩」時，應按滑鼠的何鍵？", "options": ["左鍵", "右鍵", "中間鍵", "不用按任何鍵"], "answer": "右鍵" },
    { "question": "若想在 Windows 的「小畫家」繪圖軟體中畫出一個「正方形」，可利用下列哪一個輔助按鍵，再拖曳滑鼠？", "options": ["Ctrl", "Shift", "Alt", "Esc"], "answer": "Shift" },
    { "question": "系統軟體又稱為？", "options": ["應用程式", "系統程式", "物料管理程式", "程式語言"], "answer": "系統程式" },
    { "question": "一般購買電腦時，電腦廠商必須供給的軟體是？", "options": ["系統軟體", "應用軟體", "套裝軟體", "自製軟體"], "answer": "系統軟體" },
    { "question": "公用程式屬於什麼軟體？", "options": ["應用軟體", "系統軟體", "自製軟體", "套裝軟體"], "answer": "系統軟體" },
    { "question": "應用軟體又稱為？", "options": ["公用程式", "應用程式", "作業系統", "語言翻譯程式"], "answer": "應用程式" },
    { "question": "為使電腦使用者能利用電腦，協助處理事務而設計的程式是？", "options": ["作業系統", "公用程式", "語言翻譯程式", "應用程式"], "answer": "應用程式" },
    { "question": "應用程式包括？", "options": ["語言翻譯程式", "作業系統", "會計系統", "公用程式"], "answer": "會計系統" },
    { "question": "下列何者不屬於應用軟體？", "options": ["語言翻譯程式", "會計系統程式", "薪資管理程式", "物料管理程式"], "answer": "語言翻譯程式" },
    { "question": "使用者自行設計和委托他人代為設計的軟體是？", "options": ["系統軟體", "工具軟體", "套裝軟體", "自製軟體"], "answer": "自製軟體" },
    { "question": "軟體設計公司開發出來的各種軟體，其具有某些特定的功能與用途的軟體一般稱為？", "options": ["防毒軟體", "系統軟體", "套裝軟體", "作業系統"], "answer": "套裝軟體" },
    { "question": "作業系統又稱？", "options": ["Excel", "OS", "PreMOUS", "MOCC"], "answer": "OS" },
    { "question": "在視窗作業系統中，要切換不同的輸入法，可以操作下列何種組合鍵？", "options": ["Ctrl+Backspace", "Alt+Space", "Ctrl+Enter", "Crtl+Shift"], "answer": "Crtl+Shift" },
    { "question": "在視窗作業環境中，於圖示上按滑鼠右鍵產生的快顯功能表不提供下列何種功能？", "options": ["排列圖示", "刪除", "複製", "建立捷徑"], "answer": "排列圖示" },
    { "question": "在視窗作業系統中，若要切換中、英文輸入法顯示時，可以操作下列何種組合鍵？", "options": ["Ctrl+Backspace", "Alt+Space", "Ctrl+Space", "Crtl+Enter"], "answer": "Ctrl+Space" },
    { "question": "文件中全形字與半形字所占的記憶體大小，下列敘述何者正確？", "options": ["全形字為 1 Byte，半形字為 1 Byte", "全形字為 1 Byte，半形字為 2 Bytes", "全形字為 2 Bytes，半形字為 1 Byte", "全形字為 2 Bytes，半形字為 2 Bytes"], "answer": "全形字為 2 Bytes，半形字為 1 Byte" },
    { "question": "在「Word」文書處理軟體中，當文件內容超過一個視窗所能顯示的範圍時，若要查看文件下方的內容，操作方法為下列何者？", "options": ["水平捲軸向右拖曳", "水平捲軸向左拖曳", "垂直捲軸向上拖曳", "垂直捲軸向下拖曳"], "answer": "垂直捲軸向下拖曳" },
    { "question": "OpenOffice.org 包含的軟體中，哪一項是針對文書處理功能開發的？", "options": ["Word", "Writer", "Notepad", "WordPro"], "answer": "Writer" },
    { "question": "下列關於 Microsoft Office 和 OpenOffice.org 的相對應用軟體對應，何者有誤？", "options": ["文書處理：Word 與 Writer", "電子試算表：Excel 與 Calc", "簡報設計：PowerPoint 與 Impress", "資料庫：Access 與 Draw"], "answer": "資料庫：Access 與 Draw" },
    { "question": "下列何者不是自由軟體？", "options": ["OpenOffice.org", "Linux", "Firefox", "WinRAR"], "answer": "WinRAR" },
    { "question": "OpenOffice.org 包含的軟體中，哪一項是針對資料庫功能開發的？", "options": ["Draw", "Calc", "Writer", "Base"], "answer": "Base" },
    { "question": "OpenOffice 套裝軟體不具有下列那一種功能的軟體？", "options": ["文書處理", "簡報軟體", "資料庫軟體", "以上皆非"], "answer": "以上皆非" },
    { "question": "當你必須設計一份建築圖，請用該用何類軟體？", "options": ["CAD", "CAI", "CAM", "GPS"], "answer": "CAD" },
    { "question": "DTP 是什麼的簡稱？", "options": ["電子佈告欄", "自動付款機", "桌上排版系統", "無人銀行"], "answer": "桌上排版系統" },
    { "question": "小明的爸爸是一家中小企業的老闆，公司最近買了一套薪資管理系統，這套軟體是屬於？", "options": ["管理資訊系統", "專家系統", "決策支援系統", "輔助製造系統"], "answer": "管理資訊系統" },
    { "question": "Word 視窗中，能夠輸入和編修文件的地方，稱之為？", "options": ["快顯功能表", "工具列", "捲軸", "文件編輯區"], "answer": "文件編輯區" },
    { "question": "在 Word 中，開啟新檔案時，其預設的副檔名為？", "options": ["BAS", "DOC", "DBF", "TXT"], "answer": "DOC" },
    { "question": "在 Word 或 Excel 中，欲設定文件紙張大小，可由下列那一個選項設定？", "options": ["『格式／段落／行與分隔設定』", "『檔案／版面設定』", "『檔案／列印』", "『格式／樣式』"], "answer": "『檔案／版面設定』" },
    { "question": "下列何者為文書處理檔的類型？", "options": [".doc", ".xls", ".ppt", ".wav"], "answer": ".doc" },
    { "question": "下列何者為電子試算表檔的類型？", "options": [".doc", ".xls", ".ppt", ".mid"], "answer": ".xls" },
    { "question": "下列何者為簡報軟體檔的類型？", "options": [".doc", ".xls", ".ppt", ".avi"], "answer": ".ppt" },
    { "question": "搜集、記載或剪貼資料時，須經過編修或重新組合，這種增減文字資料的整理動作稱為？", "options": ["程式語言", "文書處理", "試算表", "電腦繪圖"], "answer": "文書處理" },
    { "question": "無論中、英文資料都可迅速加以修改編排，且增加表格製作的套裝軟體稱為？", "options": ["程式語言", "電腦繪圖", "文書處理", "試算表"], "answer": "文書處理" },
    { "question": "下列何者軟體主要使用在預算表編製與財務規劃方面？", "options": ["DOS", "OS/2", "PC-DOS", "Excel"], "answer": "Excel" },
    { "question": "每按一下可刪除游標左邊的字元，游標並會自動往左移一位為下列何者？", "options": ["退位鍵", "控制鍵", "跳離鍵", "輸入鍵"], "answer": "退位鍵" },
    { "question": "在「Word」文書處理軟體中，當文件內容超過一個視窗所能顯示的範圍時，若要查看文件上方的內容，操作方法為下列何者？", "options": ["水平捲軸向右拖曳", "水平捲軸向左拖曳", "垂直捲軸向上拖曳", "垂直捲軸向下拖曳"], "answer": "垂直捲軸向上拖曳" },
    { "question": "在「Word」文書處理軟體中，當文件內容超過一個視窗所能顯示的範圍時，若要查看文件左方的內容，操作方法為下列何者？", "options": ["水平捲軸向右拖曳", "水平捲軸向左拖曳", "垂直捲軸向上拖曳", "垂直捲軸向下拖曳"], "answer": "水平捲軸向左拖曳" },
    { "question": "在「Word」文書處理軟體中，當文件內容超過一個視窗所能顯示的範圍時，若要查看文件右方的內容，操作方法為下列何者？", "options": ["垂直捲軸向下拖曳", "水平捲軸向左拖曳", "垂直捲軸向上拖曳", "水平捲軸向右拖曳"], "answer": "水平捲軸向右拖曳" },
    { "question": "在「Word」文書處理軟體中，要列印資料時，操作步驟為何？", "options": ["檔案／版面設定", "檔案／列印", "檔案／預覽列印", "檔案／傳送到"], "answer": "檔案／列印" },
    { "question": "在「Word」文書處理軟體中，欲選取連續的區塊文字時，可在文字起點按滑鼠左鍵一下，接著按下列那個按鍵不放，再到文字終點按滑鼠左鍵一下，即可將文字選取起來？", "options": ["Ctrl", "Alt", "Shift", "Enter"], "answer": "Shift" },
    { "question": "在「Word」文書處理軟體中，欲使用鍵盤選取文字時，下列敘述何者錯誤？", "options": ["Shift + Ctrl + Home 可向上選取整份文件", "Ctrl + Z 可選取整份文件", "Shift +方向鍵可選取連續的區塊", "Shift + Ctrl + End可向下選取整份文件"], "answer": "Ctrl + Z 可選取整份文件" },
    { "question": "在「Word」文書處理軟體中，關於表格功能的敘述下列何者錯誤？", "options": ["不可以自訂列高", "可以合併儲存格", "可以分割儲存格", "可套用表格自動格式設定"], "answer": "不可以自訂列高" },
    { "question": "在「Word」文書處理軟體中，選取圖片後，再以滑鼠拖曳圖片，其功能為下列何者？", "options": ["調整圖片大小", "刪除圖片", "複製圖片", "搬移圖片"], "answer": "搬移圖片" },
    { "question": "在「Word」文書處理軟體的工作環境中，下列何者可顯示文件檔名？", "options": ["標題列", "視窗控制鈕", "功能表列", "工具列"], "answer": "標題列" },
    { "question": "在「Word」文書處理軟體的工作環境中，下列何者可縮小視窗、還原視窗、將視窗放到最大？", "options": ["標題列", "視窗控制鈕", "功能表列", "工具列"], "answer": "視窗控制鈕" },
    { "question": "在「Word」文書處理軟體的工作環境中，下列何者內含所有「Word」的指令？", "options": ["標題列", "視窗控制鈕", "功能表列", "編輯區"], "answer": "功能表列" },
    { "question": "在「Word」文書處理軟體的工作環境中，可在下列何者輸入文字、插入圖案或表格？", "options": ["標題列", "視窗控制鈕", "功能表列", "文字編輯區"], "answer": "文字編輯區" },
    { "question": "在「Word」文書處理軟體的工作環境中，下列何者可標示文字編輯區寬度的水平位置？", "options": ["水平尺規", "垂直尺規", "垂直捲動軸", "水平捲動軸"], "answer": "水平尺規" },
    { "question": "在「Word」文書處理軟體的工作環境中，下列何者可標示文字編輯區高度的垂直位置？", "options": ["水平尺規", "垂直尺規", "垂直捲動軸", "水平捲動軸"], "answer": "垂直尺規" },
    { "question": "在「Word」文書處理軟體的工作環境中，若版面大於水平顯示時，可調整下列何者，以得到最佳的版面？", "options": ["水平尺規", "垂直尺規", "垂直捲動軸", "水平捲動軸"], "answer": "水平捲動軸" },
    { "question": "在「Word」文書處理軟體的工作環境中，若版面大於垂直顯示時，可調整下列何者，以得到最佳的版面？", "options": ["水平尺規", "垂直尺規", "垂直捲動軸", "水平捲動軸"], "answer": "垂直捲動軸" },
    { "question": "在「Word」文書處理軟體的工作環境中，在何處會顯示文件目前的頁碼及總頁數？", "options": ["繪圖工具列", "狀態列", "標題列", "一般工具列"], "answer": "狀態列" },
    { "question": "在「Word」文書處理軟體的工作環境中，「剪下」、「貼上」、「複製」等指令，是位於哪一個功能表中？", "options": ["檔案", "編輯", "格式", "工具"], "answer": "編輯" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要另存新檔時，可使用何種功能表列？", "options": ["檔案", "編輯", "格式", "工具"], "answer": "檔案" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要儲存檔案時，可使用何種功能表列？", "options": ["檔案", "編輯", "格式", "工具"], "answer": "檔案" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要開啟舊檔案時，可使用何種功能表列？", "options": ["編輯", "檔案", "插入", "檢視"], "answer": "檔案" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要開啟一份新的文件時，可使用何種功能表列？", "options": ["編輯", "檔案", "插入", "檢視"], "answer": "檔案" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要複製資料時，可使用何種功能表列？", "options": ["編輯", "檔案", "插入", "檢視"], "answer": "編輯" },
    { "question": "在「Word」文書處理軟體的工作環境中，想要貼上資料時，可使用何種功能表列？", "options": ["編輯", "檔案", "插入", "檢視"], "answer": "編輯" },
    { "question": "「網際網路」的普及使得電腦能幫助人類從事更多的研究與活動，其英文名稱為？", "options": ["Internet", "FTP", "Hinet", "Seednet"], "answer": "Internet" },
    { "question": "下列何者為「電子佈告欄」的英文簡稱？", "options": ["WWW", "CAI", "CAD", "BBS"], "answer": "BBS" },
    { "question": "下列何者為「電子資料交換」的英文簡稱？", "options": ["OA", "ISP", "EDI", "VR"], "answer": "EDI" },
    { "question": "下列何者為台灣目前最大的網際網路服務供應商？", "options": ["Hinet", "Tanet", "Seednet", "Kimo"], "answer": "Hinet" },
    { "question": "TANet 意指？", "options": ["網際網路", "網路伺服器", "臺灣學術網路", "廣域網路"], "answer": "臺灣學術網路" },
    { "question": "下列敘述何者錯誤？", "options": ["區域網路簡稱WAN", "整合服務數位網路 ISDN", "全球資訊網 WWW", "國家資訊基礎建設簡稱 NII"], "answer": "區域網路簡稱WAN" },
    { "question": "下列那一種上網的速率頻寬較大？", "options": ["T3", "T2", "T1", "256K"], "answer": "T3" },
    { "question": "Internet 是一種？", "options": ["操作系統", "區域網路操作系統", "網際網路", "內部連接系統"], "answer": "網際網路" },
    { "question": "由全世界大大小小的網路連接而成的全球性網路稱為？", "options": ["區域網路 (LAN)", "企業網路 (Intranet)", "網際網路 (Internet)", "環狀網路 (Ring Network)"], "answer": "網際網路 (Internet)" },
    { "question": "目前國內最大的學術性 Internet 服務機構是？", "options": ["SeedNet", "HiNet", "TANet", "BitNet"], "answer": "TANet" },
    { "question": "網域名稱中，「.edu」代表的是何種單位？", "options": ["公司行號", "政府機關", "學術教育機構", "財團法人及組織單位"], "answer": "學術教育機構" },
    { "question": "將網際網路的架構應用在企業營運的架構，模擬成網際網路上的各種服務，此種網路稱為？", "options": ["WAN", "Internet", "Intranet", "ISDN"], "answer": "Intranet" },
    { "question": "下列敘述何者錯誤？", "options": ["區域網路簡稱 LAN", "整合服務數位網路簡稱 ISDN", "台灣學術網路簡稱 TANet", "國家資訊基礎建設簡稱 GlI"], "answer": "國家資訊基礎建設簡稱 GlI" },
    { "question": "【國家資訊基礎建設】英文簡稱為？", "options": ["BBS", "CNN", "NII", "WWW"], "answer": "NII" },
    { "question": "網域名稱中，教育部的網址為 www.edu.tw, 下列那一個是代表教育單位？", "options": ["www", "edu", "tw", "以上皆是"], "answer": "edu" },
    { "question": "進入網路瀏覽器程式後，若欲進入 Hinet 多媒體網站，則可在「位址」命令列輸入命令如下？", "options": ["ftp://hinet.net.com", "http://hinet.net.tw", "ftp://www.hinet.net", "http://www.hinet.net"], "answer": "http://www.hinet.net" },
    { "question": "Hinet、SeedNet 及 TANet 是服務大家上網的機構及公司，我們稱之為？", "options": ["NIC(網路訊息中心)", "WWW(全球資訊網)", "NI(網路仲介)", "ISP(網際網路服務提供者)"], "answer": "ISP(網際網路服務提供者)" },
    { "question": "瀏覽器開啟後所看到的第一個網頁稱之為？", "options": ["首頁", "底部", "找尋格式", "Gopher 資訊系統伺服器"], "answer": "首頁" },
    { "question": "網域名稱中，「.org」代表的是何種單位？", "options": ["公司行號", "政府機關", "國防軍事單位", "財團法人及組織單位"], "answer": "財團法人及組織單位" },
    { "question": "http://www.cea.org.tw 的網址中，那一段代表國家或地理區域？", "options": ["www", "cea", "org", "tw"], "answer": "tw" },
    { "question": "全球資訊網 (World Wide Web) 使用最普遍是哪一種檔案格式？", "options": [".doc", ".htm", ".txt", ".dbf"], "answer": ".htm" },
    { "question": "WWW 是何者的縮寫？", "options": ["World.Wide.Web", "World.Web Wide", "Web WorldWide", "WideWeb World"], "answer": "World.Wide.Web" },
    { "question": "test@xxx.com.tw 中@的左邊代表的是？", "options": ["個人的名字", "個人的網址", "個人的密碼", "個人的帳號"], "answer": "個人的帳號" },
    { "question": "在設定網路連線時，POP3 伺服器是指？", "options": ["收信伺服器", "寄信伺服器", "檔案伺服器", "網站伺服器"], "answer": "收信伺服器" },
    { "question": "在設定網路連線時，SMTP 伺服器是指？", "options": ["收信伺服器", "寄信伺服器", "檔案伺服器", "網站伺服器"], "answer": "寄信伺服器" },
    { "question": "將多種型態的資訊如語音、視訊、傳真等整合在一個網路服務稱為？", "options": ["整體服務數位網路", "區域網路", "加值型網路", "以上皆非"], "answer": "整體服務數位網路" },
    { "question": "在電子郵件軟體中，每一封傳送出去的信件都會保留一份在？", "options": ["寄件備份", "寄件匣", "草稿", "刪除的郵件"], "answer": "寄件匣" },
    { "question": "哪一種網路應用，使用者可以下載或上傳檔案？", "options": ["FTP", "WWW", "Gopher", "News"], "answer": "FTP" },
    { "question": "下列那個不是一般使用者進入及連接網際網路所必需要具備的？", "options": ["使用者帳號", "密碼", "撥接帳號", "FTP 軟體"], "answer": "FTP 軟體" },
    { "question": "目前電腦通訊傳輸媒體的傳輸速度以何種介質最快？", "options": ["雙絞線", "光纖", "電話線", "同軸電纜"], "answer": "光纖" },
    { "question": "兩部電腦互相溝通，用更專業的說法稱為？", "options": ["電腦打字", "電腦通訊", "電腦排版", "電腦繪圖"], "answer": "電腦通訊" },
    { "question": "所謂的「電腦網路」是指？", "options": ["一部電腦連線", "兩部硬碟機連線", "兩部印表機連線", "兩部或兩部以上電腦連線"], "answer": "兩部或兩部以上電腦連線" },
    { "question": "HiNet、SeedNet 及 TANet 是服務大家上網的機構及公司，通常統稱為何？", "options": ["Internet", "WWW", "BBS", "ISP"], "answer": "ISP" },
    { "question": "企圖闖入到未經授權的電腦，以竊取資料者稱為下列何者？", "options": ["學者", "駭客", "軟體工程師", "硬體工程師"], "answer": "駭客" },
    { "question": "下列何者是目前國內最大的學術性 Internet 服務機構？", "options": ["SeedNet", "HiNet", "TANet", "ByNet"], "answer": "TANet" },
    { "question": "在網際網路中，下列何者代表組織單位的性質？", "options": [".org", ".com", ".gov", ".edu"], "answer": ".org" },
    { "question": "在網際網路中，下列何者代表公司行號或商業團體的性質？", "options": [".org", ".com", ".gov", ".edu"], "answer": ".com" },
    { "question": "在網際網路中，下列何者代表政府機關的性質？", "options": [".com", ".org", ".gov", ".edu"], "answer": ".gov" },
    { "question": "在網際網路中，下列何者代表教育單位的性質？", "options": [".com", ".org", ".gov", ".edu"], "answer": ".edu" },
    { "question": "網際網路最初設計的目的為下列何者？", "options": ["政治", "行政", "學術", "醫療"], "answer": "行政" },
    { "question": "下列何者系統網路是連接不同國家系統的網路？", "options": ["Local Area Network", "Metropolition Area Network", "Wide Area Network", "Internet Area Network"], "answer": "Metropolition Area Network" },
    { "question": "下列何者是區域網路的簡稱？", "options": ["BBS", "LAN", "Internet", "DOS"], "answer": "LAN" },
    { "question": "下列何者是網際網路的英文名稱？", "options": ["BBS", "LAN", "Internet", "DOS"], "answer": "Internet" },
    { "question": "網際網路最初是以哪一個國家所制定的標準為基礎所發展出來的世界性廣域網路？", "options": ["美國", "英國", "法國", "德國"], "answer": "美國" },
    { "question": "下列何者不是電腦主要處理儲存的資料？", "options": ["文字", "程式", "電源", "聲音"], "answer": "電源" },
    { "question": "下列何者是由教育部管理的網路？", "options": ["HiNet", "TANeT", "SeedNeT", "CDPCNET"], "answer": "TANeT" },
    { "question": "早期的網際網路的溝通介面是以哪一種為主？", "options": ["文字", "聲音", "影片", "程式"], "answer": "文字" },
    { "question": "HiNet 是由下列哪個單位所建立的網路？", "options": ["教育部", "中華電信", "國防部", "經濟部"], "answer": "中華電信" },
    { "question": "WWW 為？", "options": ["全國資訊網", "電腦資訊網", "美國資訊網", "全球資訊網"], "answer": "全球資訊網" },
    { "question": "數據機中傳輸為 9600BPS，意思是指每秒鐘可傳送 9.6K？", "options": ["位元", "字元", "位元組", "字元組"], "answer": "位元" },
    { "question": "學校的網路若是使用 RJ-45 的方式佈線，下列那一種設備可以用來聯接 RJ-45？", "options": ["集線器", "訊號增強器", "路由器", "閘道器"], "answer": "集線器" },
    { "question": "學校的電腦網路頻寬如果為 100M, 網路下後面需接一條的網路線，網路線的接頭類似電話線接頭，我們稱為何種接頭？", "options": ["BNC", "RJ-45", "FDD", "FTP"], "answer": "RJ-45" },
    { "question": "電腦交換訊息要透過溝通媒介來溝通，此「溝通媒介」指的是？", "options": ["電源線", "信號線", "接地線", "音源線"], "answer": "信號線" },
    { "question": "電腦的通訊協定一共分為幾層？", "options": ["五層", "六層", "七層", "八層"], "answer": "七層" },
    { "question": "下列何者是數據機的英文名稱？", "options": ["Internet", "LAN", "modem", "WAN"], "answer": "modem" },
    { "question": "IE 瀏覽器保留上網的資料可以在那一選項查知？", "options": ["搜尋", "我的最愛", "記錄", "首頁"], "answer": "記錄" },
    { "question": "上網到教育部網站，已知教育部的網址為 www.edu.tw，你欲查知它的真正 IP 位址，可以用下列那一命令？", "options": ["ping", "pack", "DIR", "EXIT"], "answer": "ping" },
    { "question": "網際網路(Internet)使用哪一種網路協定？", "options": ["TCP/IP", "IPX/SPX", "NetBEUI", "X.25"], "answer": "TCP/IP" },
    { "question": "http://www.ntnu.edu.tw 的網址中，那一段代表這個單位的網域？", "options": ["www.ntnu.edu.tw", "ntnu.edu.tw", "edu.tw", "tw"], "answer": "ntnu.edu.tw" },
    { "question": "URL 的表示法為：http://www.hinet.net/index.htm，其中 http://為？", "options": ["路徑名稱", "傳輸協定", "網站位址", "檔案名稱"], "answer": "傳輸協定" },
    { "question": "設定下列哪一項，可以讓你使用 IE6 瀏覽網站時，減少連外網路的負荷？", "options": ["設定 History", "設定 Proxy 伺服器", "使用 Autocomplete", "設定我的最愛"], "answer": "設定 Proxy 伺服器" },
    { "question": "當你上網時，你的電腦與雅虎奇摩網站傳輸網路兩端之節點可以在同一時間互相傳輸及接受資料的方式稱為？", "options": ["雙工式(duplex)", "並列傳輸", "單工式(simplex)", "電路交換"], "answer": "雙工式(duplex)" },
    { "question": "印表機以 USB 方式與電腦主機的連接方式採？", "options": ["全雙工", "並列傳輸", "序列傳輸", "Game Port"], "answer": "序列傳輸" },
    { "question": "下列有關 ADSL 的描述何者有誤？", "options": ["非對稱數位用戶線路", "以電話線做傳輸媒介", "無法同時上網及講電話", "上傳及下載資料時的傳輸速率不對稱"], "answer": "無法同時上網及講電話" },
    { "question": "數據機（Modem）的作用主要是在於？", "options": ["提昇瀏覽網頁的速度", "將電腦的數位訊號與電話線中的類比訊號互相轉換", "網路傳輸線和電腦之間的連接介面", "增加電腦的運算能力"], "answer": "將電腦的數位訊號與電話線中的類比訊號互相轉換" },
    { "question": "目前 ADSL 的傳輸速率常見有 2M/256K，以下描述何者正確？", "options": ["下載速率為 2MB/sec", "上傳速率為 256Kbps", "上傳速率大於下載速率", "下載速率約為上傳速率的 32 倍"], "answer": "上傳速率為 256Kbps" },
    { "question": "欲連上網際網路 Windows 的通訊協定一定要加上那一個協定？", "options": ["SSL", "TCP/IP", "TCP", "IPX/SPX"], "answer": "TCP/IP" },
    { "question": "下列那一功能是瀏覽器軟體不能提供的服務？", "options": ["WWW", "Mail", "FTP", "解毒"], "answer": "解毒" },
    { "question": "網際網路可以使用的資源有那些？", "options": ["WWW", "Mail", "FTP", "以上皆是"], "answer": "以上皆是" },
    { "question": "Kuro 的網路音樂分享、ezPeer 的網路多媒體影音分享等網際網路服務，在程式架構上是採取什麼架構？", "options": ["Master-Slave", "Peer-to-Peer", "Client-Server", "File Sharing"], "answer": "Peer-to-Peer" },
    { "question": "中華電信公司提供的 HiNet 網路是屬於？", "options": ["大都會網路", "區域網路", "廣域網路", "無線網路"], "answer": "廣域網路" },
    { "question": "下列何者不是採用「串列」的方式來傳輸資料？", "options": ["網路卡和 ADSL", "DRAM 和 CPU", "滑鼠和 USB", "硬碟和 SATA 介面"], "answer": "DRAM 和 CPU" },
    { "question": "下列何者是在家中使用 ADSL 上網時最基本的配備？", "options": ["網路卡、數據機、集線器", "電話線、網路卡、數據機", "無線 AP、網路卡、IP 分享器", "數據專線、網路卡、數據機"], "answer": "電話線、網路卡、數據機" },
    { "question": "哪一種網路應用，使用者可以下載或上傳檔案？", "options": ["FTP", "WWW", "Gopher", "News"], "answer": "FTP" },
    { "question": "關於電腦網路的功用何者不正確？", "options": ["能提供硬體共享", "能提供資料共享", "使用者彼此可以互傳訊息", "可在家中利用遠端朋友的數據機上網"], "answer": "可在家中利用遠端朋友的數據機上網" },
    { "question": "下列何者為區域網路？", "options": ["在家裡用集線器及私人 IP 的方式架設形成的網路", "在學校和學校之間利用閘道器或路由器連結的網路", "在一個都市裡使用手機基地台連結架設的網路", "在偏遠山區使用衛星傳播的網路"], "answer": "在家裡用集線器及私人 IP 的方式架設形成的網路" },
    { "question": "下列關於網路存取型態的敘述，何者有誤？", "options": ["主從式網路上的客戶端可以互相分享資源", "點對點網路上的每一台電腦都可以是伺服器或客戶端", "Foxy、e-Donkey、Kuro 等軟體的資料下載模式屬於點對點網路", "Internet 上的 WWW 服務採用點對點式"], "answer": "Internet 上的 WWW 服務採用點對點式" },
    { "question": "網路設備路由器（Router），其主要運作層次為？", "options": ["網路層", "傳輸層", "中繼層", "大氣層"], "answer": "網路層" },
    { "question": "國際標準組織（ISO）制訂的開放式系統連接模型（OSI）中，E-mail 服務是屬於下列哪一層？", "options": ["資料鏈結層", "網路層", "傳輸層", "應用層"], "answer": "應用層" },
    { "question": "何種網際網路(Internet)服務, 可遠端簽入主機進行工作？", "options": ["Gopher", "FTP", "Telnet", "WWW"], "answer": "Telnet" },
    { "question": "你公司的使用者希望可以進行郵件收送，你需要幫他裝哪一種軟體？", "options": ["RealPlayer", "Outlook Express", "NetMeeting", "FTP"], "answer": "Outlook Express" },
    { "question": "兩台電腦要交換訊息，就要使用同樣的？", "options": ["電腦", "印表機", "通訊協定", "螢幕"], "answer": "通訊協定" },
    { "question": "IP 位址通常是由四組數字所組成的，每組數字範圍為何？", "options": ["0-127", "0-255", "0-512", "0-1024"], "answer": "0-255" },
    { "question": "在網際網路中，「http:」代表下列何種意義？", "options": ["一種通訊協定", "一種名字", "網頁名稱", "路徑"], "answer": "一種通訊協定" },
    { "question": "下列那一項的功能，使人們得以在自己的辦公室，經由視訊設備見到遠方的夥伴，並且互相交談？", "options": ["隨選視訊", "視訊會議", "微縮技術", "電子郵件"], "answer": "視訊會議" },
    { "question": "透過通訊網路可將辦公室各部門公文、文件或信函迅速傳達至各地收件人的終端機前的功能稱為？", "options": ["隨選視訊", "電傳視訊", "電傳會議", "電子郵件"], "answer": "電子郵件" },
    { "question": "電子商務的簡稱是？", "options": ["EDI", "E-mail", "EC", "EP"], "answer": "EC" },
    { "question": "住在中壢的小明在家裡想要和住在桃園的同學討論功課，可利用那種方式面對面交談？", "options": ["電子郵件", "視訊會議", "電子佈告欄", "聊天室"], "answer": "視訊會議" },
    { "question": "買賣雙方透過電腦與網路連線的方式進行交易，稱為？", "options": ["電子購物", "電子資料文換", "電子郵件", "視訊會議"], "answer": "電子購物" },
    { "question": "用 Outlook Express 寄郵件，如果常用的收件人可以放在？", "options": ["收件匣", "寄件匣", "刪除的郵件", "通訊錄"], "answer": "通訊錄" },
    { "question": "在 WEB 化的電子郵系統中，利用瀏覽器收發信件的操作中，輸入帳號及？", "options": ["住址", "電碼", "電話", "密碼"], "answer": "密碼" },
    { "question": "如果你在 IE 中，要將常用的網址記在電腦中，可以加到？", "options": ["我的最愛", "標題列", "網路芳鄰", "工具列"], "answer": "我的最愛" },
    { "question": "在網路上使用聊天室，需尊重別人的發言權及自己的隱私，所以不可？", "options": ["攻擊別人言論", "公佈真正帳號", "公佈真正姓名", "以上皆是"], "answer": "以上皆是" },
    { "question": "電子郵件不具下列那一個功能？", "options": ["附加檔案", "線上聊天", "附加圖片", "附加簽名"], "answer": "線上聊天" },
    { "question": "下列那一種功能在 Internet 上不能達成？", "options": ["聊天室", "多人對打遊戲", "傳送影像", "以上皆非"], "answer": "以上皆非" },
    { "question": "檔案分享的功能下列那一設備不能分享？", "options": ["磁碟機", "光碟機", "印表機", "螢幕"], "answer": "螢幕" },
    { "question": "電子郵件中，在使用 Outlook Express 時，前面有標示一個迴紋針，表示郵件有？", "options": ["未讀取", "安全提示", "檔案附件", "已讀取"], "answer": "檔案附件" },
    { "question": "下列何者是事先建立的一個文字檔，於每次撰寫新郵件時可直接加入於信件的末端？", "options": ["收件匣", "寄件匣", "簽名檔", "通訊錄"], "answer": "簽名檔" },
    { "question": "將多種型態的資訊如語音、視訊、傳真等整合在一個網路服務稱為？", "options": ["整體服務數位網路", "區域網路", "加值型網路", "以上皆非"], "answer": "整體服務數位網路" },
    { "question": "在 Internet 上，專門提供使用者分享訊息、交換意見、討論相關主題等等的地方稱為什麼？", "options": ["WWW 資訊站", "網路論壇系統", "郵件伺服器", "Gopher"], "answer": "網路論壇系統" },
    { "question": "電腦名詞 BBS 指的是什麼？", "options": ["電子郵件", "電子佈告欄", "區域網路", "網際網路"], "answer": "電子佈告欄" },
    { "question": "IE 瀏覽器保留上網的資料可以在那一選項查知？", "options": ["搜尋", "我的最愛", "記錄", "首頁"], "answer": "記錄" },
    { "question": "電子郵件中，有一個人的帳號為 COMPUTER，而他的電子郵件主機為 mail.edu.tw，如果你要寄信給他，那他的帳號為？", "options": ["computer@mail.edu.tw", "computer$mail.edu.tw", "computer#mail.edu.tw", "computer!mail.edu.tw"], "answer": "computer@mail.edu.tw" },
    { "question": "下列何者代表「企業間網路」？", "options": ["HiNet", "Internet", "Intranet", "Extranet"], "answer": "Extranet" },
    { "question": "電腦網路的「頻寬」係指下列何者？", "options": ["傳輸速度很快的網路系統", "每秒可傳送多少個位元（bps）", "傳輸媒體的粗細", "網路卡的傳輸能力"], "answer": "每秒可傳送多少個位元（bps）" },
    { "question": "FTP 是網際網路（Internet）的一項服務，其功能為？", "options": ["遠端登錄", "電子郵件", "檔案傳輸", "電傳視訊"], "answer": "檔案傳輸" },
    { "question": "在瀏覽器的網址列輸入「140.120.1.20」，這四組數字代表的是？", "options": ["通訊協定", "網頁名稱", "使用者帳號", "IP 位址"], "answer": "IP 位址" },
    { "question": "在 WWW 中共同的協定是，當游標變為手的圖示時，表示此處可以？", "options": ["取郵件", "超連結", "上傳資料", "沒動作"], "answer": "超連結" },
    { "question": "網路上「即時通」的使用，下列那一種不能達成？", "options": ["傳文字", "傳訊息", "呼叫人", "遠端安裝系統"], "answer": "遠端安裝系統" },
    { "question": "檔案分享的功能下列那一設備不能分享？", "options": ["磁碟機", "光碟機", "印表機", "螢幕"], "answer": "螢幕" },
    { "question": "你要在區域網路中，知道網路上目前有那些電腦你可以利用下列那一功能查知？", "options": ["資料夾", "網路芳鄰", "資源回收筒", "公事包"], "answer": "網路芳鄰" },
    { "question": "下列何者是事先建立的一個文字檔，於每次撰寫新郵件時可直接加入於信件的末端？", "options": ["收件匣", "寄件匣", "簽名檔", "通訊錄"], "answer": "簽名檔" },
    { "question": "下列有關 Blog 的敘述，何者錯誤？", "options": ["可讓網友回應或張貼訊息", "屬於在網路上提供個人網頁空間的一種方式", "通常是免費會員制", "通常是屬於個人私密空間，不宜對外開放"], "answer": "通常是屬於個人私密空間，不宜對外開放" },
    { "question": "下列哪一種網際網路的服務最適合用來上傳和下載檔案？", "options": ["MSN", "FTP", "Skype", "WWW"], "answer": "FTP" },
    { "question": "在網際網路中，「FTP」代表下列何種意義？", "options": ["聊天服務", "電子郵件服務", "檔案傳輸服務", "新聞群組服務"], "answer": "檔案傳輸服務" },
    { "question": "在 Internet 服務中，下列何者提供即時與其他使用者互動的功能？", "options": ["聊天室", "電子郵件", "新聞群組", "FTP"], "answer": "聊天室" },
    { "question": "使用 Outlook Express 發送信件時，要將一封信一次發給多位收信者，可使用下列何種方法？", "options": ["選項中的傳送設定", "設定群組", "收件匣助理員", "使用附件夾帶"], "answer": "設定群組" },
    { "question": "在 Outlook Express 中，「全部回覆」是指下列何種意義？", "options": ["回覆給通訊錄中的所有人", "回覆給指定的所有人", "回覆給所有有收到郵件的人及寄件者", "回覆給所有群組"], "answer": "回覆給所有有收到郵件的人及寄件者" },
    { "question": "在接收郵件時，若郵件上出現迴紋針符號，表示此封郵件為何種意義？", "options": ["為普通信件", "為急件", "含有附加檔案的郵件", "帶有病毒的郵件"], "answer": "含有附加檔案的郵件" },
    { "question": "在 Outlook Express 中，如何更改所選信件匣中信件的排序？", "options": ["檢視功能表的排列方式", "檢視功能表的篩選", "收件匣助理員", "匯出郵件"], "answer": "檢視功能表的排列方式" },
    { "question": "電子郵件不僅收費低廉，最快可能在多久時間內寄送或收取信件？", "options": ["數分鐘", "一天", "二天", "三天"], "answer": "數分鐘" },
    { "question": "電子郵件又稱？", "options": ["A-Mail", "C-Mail", "E-Mail", "F-Mail"], "answer": "E-Mail" },
    { "question": "下列何者不是電腦病毒感染的途徑？", "options": ["磁碟片", "網路", "電子郵件", "合法之原版光碟"], "answer": "合法之原版光碟" },
    { "question": "在網路上交易，如果要有安全考慮，在通訊中需加入那一種協定？", "options": ["SSL", "TCP/IP", "NETBEUI", "IPX/SPX"], "answer": "SSL" },
    { "question": "日前調查局破獲地下光碟複製工廠，並起訴若干負責人與工作人員，請問其拷貝光碟的行為，係違反下列何者有關智慧財產權(IPR)之法律？", "options": ["著作權法", "專利法", "商標法", "營業秘密法"], "answer": "著作權法" },
    { "question": "下列那個處理方向的考量，不是資料安全議題的核心問題？", "options": ["資料存取控制處理", "資料壓縮處理", "資料備份處理", "資料損毀復原處理"], "answer": "資料壓縮處理" },
    { "question": "資訊安全必須保護資訊資產的？", "options": ["機動性、可用性及完整性", "完整性、可攜性及機動性", "機密性、方便性及可讀性", "可用性、完整性及機密性"], "answer": "可用性、完整性及機密性" },
    { "question": "金融卡提領現金，通常限制二十次後，必須到銀行進行補登作業，否則就不得再用金融卡提領現金，這種做法在應用系統控制方面屬於哪一種控制？", "options": ["處理控制", "資料檔案控制", "輸入控制", "輸出控制"], "answer": "輸出控制" },
    { "question": "對於電腦中心的安全防護，下列何者有誤？", "options": ["不定期查閱電腦記錄", "各種作業皆需記錄", "記錄設備的使用情形", "設備的使用需經過授權"], "answer": "不定期查閱電腦記錄" },
    { "question": "下列有關「特洛依木馬型病毒 (Trojan Virus)」的敘述中，何者不正確？", "options": ["該病毒係屬於一種正常的檔案受到感染後而產生的問題檔案", "刪除該病毒的方法為直接刪除被感染的程式，而並不需藉助防毒程式來做「清除」的動作", "該病毒不會感染其他寄宿檔案", "該病毒也會攻擊 Palm 的作業系統"], "answer": "該病毒係屬於一種正常的檔案受到感染後而產生的問題檔案" },
    { "question": "透過電子郵件感染的皆屬於哪一型病毒？", "options": ["檔案型", "開機型", "混合型", "巨集型"], "answer": "巨集型" },
    { "question": "預防網路上傳送病毒，須採何種措施？", "options": ["安裝病毒檢查程式並隨時更新病毒碼", "開啟不明郵件", "開啟不明執行檔", "隨意開啟郵件上附件檔"], "answer": "安裝病毒檢查程式並隨時更新病毒碼" },
    { "question": "在網路上設定密碼上列那一種方法是較安全的？", "options": ["定時更動", "用生日", "用身分證號", "不更動"], "answer": "定時更動" },
    { "question": "下列那一種不是網路系統中資料的一種安全保護措施？", "options": ["使用密碼", "加密傳輸", "管理者密碼不更動", "使用監控軟體"], "answer": "管理者密碼不更動" },
    { "question": "網路電腦病毒通常不具有之特性？", "options": ["繁殖性", "傳播性", "隱藏性", "以上皆非"], "answer": "以上皆非" },
    { "question": "以下所述何者合乎網路禮儀？", "options": ["使用學術網路作商業用途", "將他人與你之間的私人信函轉寄給其他網友", "在信件或網頁中註明所有引述與參考資料的來源", "一次傳送 10MB 容量的信件"], "answer": "在信件或網頁中註明所有引述與參考資料的來源" },
    { "question": "網路上的病毒感染方式可能利用下列何種方法？", "options": ["電子郵件", "網站上主動傳佈", "下載開啟病毒檔案", "以上皆是"], "answer": "以上皆是" },
    { "question": "美國 911 事件中，許多金融機構中的電腦損毀，但是立即可以運作，是利用網路中的？", "options": ["遠端即時同步備份", "遠端監視", "遠端遙控", "遠端安裝"], "answer": "遠端即時同步備份" },
    { "question": "網路上電子交易，為維護安全，下列何者正確？", "options": ["需要加安全密碼", "要有公正的驗證單位", "不可以用明碼傳送", "以上皆是"], "answer": "以上皆是" },
    { "question": "企圖闖入到未授權一部電腦來竊取資料者稱為？", "options": ["駭客", "電腦書呆子", "系統操作員", "系統工程師"], "answer": "駭客" },
    { "question": "網路上的病毒感染方式可能利用下列何種方法？", "options": ["電子郵件", "網站上主動傳佈", "下載開啟病毒檔案", "以上皆是"], "answer": "以上皆是" },
    { "question": "下列何者不是一般電腦病毒的共同特性？", "options": ["需寄生在開機程式中", "具有自我複製", "需執行中毒程式，使其駐留在記憶體中，才會破壞系統", "會破壞印表機"], "answer": "會破壞印表機" },
    { "question": "病毒先潛伏在系統中，並不斷複製自己到其他程式上伺機等候，直到本身設定的條件滿足時，才會發病是？", "options": ["潛伏及傳染期", "發病期", "感染期", "空窗期"], "answer": "潛伏及傳染期" },
    { "question": "病毒會寄生在其他正常程式上，同時也把自己複製到其他正常程式中的是？", "options": ["發病期", "感染期", "空窗期", "潛伏及傳染期"], "answer": "感染期" },
    { "question": "病毒開始破壞系統，損壞磁片內容的資料時是？", "options": ["潛伏及傳染期", "感染期", "空窗期", "發病期"], "answer": "發病期" },
    { "question": "下列哪一種方式對防毒不利？", "options": ["不使用來路不明的磁片", "新軟體確定無毒貼上防寫貼紙", "常使用的資料檔案不需備份", "常用偵毒防毒程式來檢查磁片及硬碟"], "answer": "常使用的資料檔案不需備份" },
    { "question": "電腦病毒並不會經由下列何者來傳染？", "options": ["網路", "磁片", "身體", "拷貝"], "answer": "身體" },
    { "question": "電腦病毒的病發行為不包括？", "options": ["唱歌", "將磁片格式化", "系統速度加快", "佔用磁片空間"], "answer": "系統速度加快" },
    { "question": "為尊重智慧財產權，使用者應建立的正確觀念為？", "options": ["購買合法版權的軟體", "可以無限制的複製軟體", "可自行複製多份軟體，以供同學朋友使用", "使用複製軟體的用戶需付版權費給購買原版軟體者"], "answer": "購買合法版權的軟體" },
    { "question": "Excel 預設的活頁簿檔案名稱是？", "options": ["Sheet1", "Book1", "Table1", "Column1"], "answer": "Book1" },
    { "question": "在 Excel 儲存檔案的時候，檔案的副檔名為？", "options": [".exe", ".doc", ".bmp", ".xls"], "answer": ".xls" },
    { "question": "想在每一頁報表中都列印出標題欄或標題列，要在版面設定對話方塊中的哪一頁做設定？", "options": ["頁面", "邊界", "頁首/頁尾", "工作表"], "answer": "工作表" },
    { "question": "如果將儲存格中的 1997/11/24 轉換成數值形態，會顯示成以下哪一種樣式？", "options": ["35758", "35800", "31740", "US$35,758.00"], "answer": "35758" },
    { "question": "若 C1、C2、C3、C4 儲存格的值分別為 1，2，3，4 時，而 C5 儲存格的公式為 = SUM(C1：C4)，則 C5 儲存格的值為？", "options": ["10", "24", "4", "5"], "answer": "10" },
    { "question": "想計算出 A1、A2、A3、A4 儲存格的平均值，要使用下列哪一個函數？", "options": ["SUM(A1：A4)", "AVERAGE(A1：A4)", "COUNT(A1：A4)", "MAX(A1：A4)"], "answer": "AVERAGE(A1：A4)" },
    { "question": "下列何者不是影像處理軟體？", "options": ["PhotoImpact", "PhotoDraw", "Word", "PhotoShop"], "answer": "Word" },
    { "question": "要將插入點位置左邊的文字刪除時，可利用？", "options": ["BackSpace 鍵", "Ctrl 鍵", "Insert 鍵", "Delete 鍵"], "answer": "BackSpace 鍵" },
    { "question": "下列何者不是文書處理軟體？", "options": ["PEII", "Word", "HE5", "Lotus"], "answer": "Lotus" },
    { "question": "Norton AntiVirus 是屬於下列何種軟體？", "options": ["電腦防毒軟體", "資料壓縮軟體", "系統管理軟體", "檔案傳輸軟體"], "answer": "電腦防毒軟體" },
    { "question": "下列哪一種應用軟體，最適合用來設計簡報？", "options": ["Access", "FrontPage", "PowerPoint", "PhotoImpact"], "answer": "PowerPoint" },
    { "question": "下列敘述何者不正確？", "options": ["Oracle為一資料庫管理軟體", "Microsoft FrontPage 為網頁設計軟體", "Firefox 為一全球資訊網網頁瀏覽器軟體", "Notepad 可用來編輯圖片"], "answer": "Notepad 可用來編輯圖片" },
    { "question": "按一下 Word 工具列上的 <IMG SRC=\"B451.JPG\" width=25 HEIGHT=25> 鈕可以使表格內的資料？", "options": ["靠中對齊", "靠右對齊", "遞減排列", "遞增排列"], "answer": "遞增排列" },
    { "question": "要將插入點位置左邊的文字刪除時，可利用？", "options": ["BackSpace 鍵", "Ctrl 鍵", "Insert 鍵", "Delete 鍵"], "answer": "BackSpace 鍵" },
    { "question": "下列有關 Word 表格格式的敘述，何者有誤？", "options": ["可設定表格框線的色彩", "可設定表格框線的粗細", "無法為單一的儲存格設定網底色彩", "可套用表格樣式範本"], "answer": "無法為單一的儲存格設定網底色彩" },
    { "question": "若要將原編號格式為 1、2、3……的自動編號，修改為 1-1、1-2、1-3……，則應在自動編號清單交談窗的數字格式欄中，設定下列哪一種編號格式？", "options": ["x", "1-x", "x-1", "Xx"], "answer": "1-x" },
    { "question": "下列何者不是 Microsoft Word 2003 檢視文件的方法？", "options": ["整頁模式檢視", "Web 版面配置檢視", "報告模式檢視", "標準模式檢視"], "answer": "報告模式檢視" },
    { "question": "若要將 Word 檔案存成範本格式，其副檔名為？", "options": ["doc", "xls", "xlt", "dot"], "answer": "dot" },
    { "question": "在 Word 中，復原上一步編輯動作的鍵盤快速鍵為？", "options": ["Ctrl + X", "Ctrl + Y", "Ctrl + Z", "Ctrl + U"], "answer": "Ctrl + Z" },
    { "question": "欲設定紙張大小及列印方向時，應選按下列哪一個選項？", "options": ["檔案/版面設定", "格式/直書/橫書", "格式/樣式", "工具/選項"], "answer": "檔案/版面設定" },
    { "question": "在 Word「列印」交談窗中的「頁數」欄，輸入下列何者表示僅要列印文件中的第 1 頁與第 3 頁？", "options": ["1-3", "1~3", "1,3", "01:03"], "answer": "1,3" },
    { "question": "下列那一項不是合併列印功能中必須設定的內容之一？", "options": ["主文件", "字型大小", "資料來源", "合併資料與文件"], "answer": "字型大小" },
    { "question": "如果想將工作表中小於 60 的數值，以紅字粗體的方式來呈現，下列哪一種操作方法最有效率？", "options": ["逐一調整儲存格格式", "利用格式化條件設定功能", "使用取代功能", "利用填滿控點複製儲存格格式"], "answer": "利用格式化條件設定功能" },
    { "question": "在儲存格中輸入數值資料\"1234\"，預設的對齊方式為？", "options": ["置中對齊", "跨欄置中", "靠左對齊", "靠右對齊"], "answer": "靠右對齊" },
    { "question": "在電子試算表內，能展示出各個數值佔整體數值多少比例的圖表為何？", "options": ["雷達圖", "圓形圖", "函數圖", "股票圖"], "answer": "圓形圖" },
    { "question": "下列有關 PowerPoint 的敘述，何者有誤？", "options": ["一份簡報只能套用一種版面配置", "PowerPoint 可開啟名為「MsWord.ppt」的檔案", "利用母片可快速在每張投影片右下角加入學校校徽", "按 F5 鍵，可讓簡報從第一頁開始播放"], "answer": "一份簡報只能套用一種版面配置" },
    { "question": "在 Microsoft PowerPoint 中製作投影片，若要顯示所有投影片的縮圖版本，並重排投影片的順序，則在哪一種檢視模式進行最合適？", "options": ["標準模式", "投影片放映", "備忘稿", "投影片瀏覽"], "answer": "投影片瀏覽" },
    { "question": "在 PowerPoint 中，下列哪一種功能可以一次設定簡報檔案中所有投影片的格式？", "options": ["表格", "母片", "投影片切換", "投影片版面配置"], "answer": "母片" },
    { "question": "在 PowerPoint 中，簡報背景要從原套用的 Blush 樣式改為另一種樣式 Meadow，要選按『格式』中那一個選項？", "options": ["投影片版面配置", "色彩配置", "投影片設計", "背景"], "answer": "投影片設計" },
    { "question": "若要設定投影片從上一張投影片切換至下一張投影片時，有垂直百葉窗的播放特效，應在下列哪一個工作窗格中設定？", "options": ["投影片設計", "投影片切換", "投影片版面配置", "自訂動畫"], "answer": "投影片切換" },
    { "question": "在 PhotoImpact 中，下列哪一個項目提供使用者以視覺化的方式，快速的套用各種特殊效果？", "options": ["魔術棒工具", "百寶箱", "變形工具", "貝茲曲線工具"], "answer": "百寶箱" },
    { "question": "在 Excel 中，範圍「B2:C5」代表包含有幾個儲存格？", "options": ["2", "6", "8", "10"], "answer": "8" },
    { "question": "在 Excel 中，若儲存格顯示「####」時，表示？", "options": ["欄寬不足以顯示", "內容有誤", "資料已被刪除", "格式設定錯誤"], "answer": "欄寬不足以顯示" },
    { "question": "在 Excel 中，要開啟新的活頁簿，可利用下列何種方法？", "options": ["『工具／選項』", "『插入／工作表』", "檔案／開新檔案』", "『視窗／開新視窗』"], "answer": "檔案／開新檔案" },
    { "question": "如果想將工作表中小於 60 的數值，以紅字粗體的方式來呈現，下列哪一種操作方法最有效率？", "options": ["逐一調整儲存格格式", "利用格式化條件設定功能", "使用取代功能", "利用填滿控點複製儲存格格式"], "answer": "利用格式化條件設定功能" },
    { "question": "在儲存格中輸入數值資料\"1234\"，預設的對齊方式為？", "options": ["置中對齊", "跨欄置中", "靠左對齊", "靠右對齊"], "answer": "靠右對齊" },
    { "question": "在電子試算表內，能展示出各個數值佔整體數值多少比例的圖表為何？", "options": ["雷達圖", "圓形圖", "函數圖", "股票圖"], "answer": "圓形圖" },
    { "question": "下列有關 PowerPoint 的敘述，何者有誤？", "options": ["一份簡報只能套用一種版面配置", "PowerPoint 可開啟名為「MsWord.ppt」的檔案", "利用母片可快速在每張投影片右下角加入學校校徽", "按 F5 鍵，可讓簡報從第一頁開始播放"], "answer": "一份簡報只能套用一種版面配置" },
    { "question": "在 Microsoft PowerPoint 中製作投影片，若要顯示所有投影片的縮圖版本，並重排投影片的順序，則在哪一種檢視模式進行最合適？", "options": ["標準模式", "投影片放映", "備忘稿", "投影片瀏覽"], "answer": "投影片瀏覽" },
    { "question": "在 PowerPoint 中，下列哪一種功能可以一次設定簡報檔案中所有投影片的格式？", "options": ["表格", "母片", "投影片切換", "投影片版面配置"], "answer": "母片" },
    { "question": "在 PowerPoint 中，簡報背景要從原套用的 Blush 樣式改為另一種樣式 Meadow，要選按『格式』中那一個選項？", "options": ["投影片版面配置", "色彩配置", "投影片設計", "背景"], "answer": "投影片設計" },
    { "question": "若要設定投影片從上一張投影片切換至下一張投影片時，有垂直百葉窗的播放特效，應在下列哪一個工作窗格中設定？", "options": ["投影片設計", "投影片切換", "投影片版面配置", "自訂動畫"], "answer": "投影片切換" },
    { "question": "在 PhotoImpact 中，下列哪一個項目提供使用者以視覺化的方式，快速的套用各種特殊效果？", "options": ["魔術棒工具", "百寶箱", "變形工具", "貝茲曲線工具"], "answer": "百寶箱" },
    { "question": "在 Word 文件檔中，如果要在每頁的相同位置顯現浮水印，可在下列何項功能中設定？", "options": ["頁首與頁尾", "文字藝術師", "樣式", "版面設定"], "answer": "頁首與頁尾" },
    { "question": "哪一款軟體不屬於自由軟體？", "options": ["OpenOffice.org", "MySQL", "Firefox", "Visual Basic"], "answer": "Visual Basic" },
    { "question": "下列哪一種 Microsoft 的應用軟體，較適合用來編輯一個名為「Excel.doc」的檔案？", "options": ["ACCESS", "EXCEL", "POWER POINT", "WORD"], "answer": "WORD" },
    { "question": "在 Excel 的工作表中，按下 Home 鍵會？", "options": ["跳到本列之首", "跳到工作表第一列第一欄", "跳到工作表最後一列最後一欄", "跳到本列之末"], "answer": "跳到本列之首" },
    { "question": "在 Excel 中，儲存格內資料為數值，則預設對齊情況為？", "options": ["靠左", "靠右", "靠中", "不一定"], "answer": "靠右" },
    { "question": "在 Word 文件檔中，如果要在每頁的相同位置顯現浮水印，可在下列何項功能中設定？", "options": ["頁首與頁尾", "文字藝術師", "樣式", "版面設定"], "answer": "頁首與頁尾" },
]


def findAnswer(question):
    for q in questionBank:
        # print(question,q['question'])
        if q["question"] in question:
            return q["answer"]
    return None